### ISSUE TITLE
Criar função genérica para buscar cotação

### ISSUE THREAD

**Issue by gmonteeeiro** [LucasFlorence/nightmare#1]
Não acha interessante criar um função genérica para buscar a cotação? Daí seria só passar por parâmetro qual moeda tu quer, já que tu usa basicamente só o dolarhoje.com como base de dados.

**Comment by LucasFlorence** [comment]
Boa sugestão, só teria que ver como passar o parâmetro na hora de rodar o arquivo. Pois rodo esse arquivo via terminal com o exemplo: (node dolar.js) ou alguma outra forma.

**Comment by gmonteeeiro** [comment]
Bem, resolvi a questão nas PRs #3 e #4. Dá uma olhada lá
